"""Phase 2 — core records migration runner.

Reads the locked `CRM Migration Field Map` and copies rows from
`tab<Source>` to `tab<Target>` using `frappe.db.bulk_insert` after
preprocessing each row in Python. The source row's Frappe metadata
(`name`, `owner`, `creation`, `modified`, `modified_by`, `docstatus`)
is carried as-is so:
  - the audit trail survives intact,
  - re-runs are idempotent (same primary key + ignore_duplicates),
  - Phase 4 only needs to rewrite reference_doctype, never reference_name.

The runner is launchable two ways from the CRM Migration Settings form:
  - top-level "Run Migration" button (full orchestrator, all 8 sources),
  - per-tab "Migrate <Source>" Button field (single source, with a
    pre-flight that refuses if upstream lookups haven't run yet).

After each parent step, child rows belonging to *shared-schema* Table
fields (e.g. tabCRM Status Change Log rows whose parenttype was 'Lead')
are re-anchored to the new target parent doctype with one UPDATE per
child doctype. Schema-reshape children (Opportunity Item → CRM Products,
Opportunity.contact_person → CRM Deal.contacts, lost_reasons →
lost_reason) are Phase 3.
"""

from __future__ import annotations

import frappe
from frappe import _
from frappe.utils import now_datetime

from erpnext_crm_to_frappe_crm_migrator.api import activity, reshape
from erpnext_crm_to_frappe_crm_migrator.api.mapping import DYNAMIC_LINK_ROUTES
from erpnext_crm_to_frappe_crm_migrator.mapping.registry import (
	REVERSE_DOCTYPE_MAP,
	SOURCE_DOCTYPES,
)

SETTINGS_DOCTYPE = "CRM Migration Settings"
FIELD_MAP_DOCTYPE = "CRM Migration Field Map"
RUN_DOCTYPE = "CRM Migration Run"

# Source-meta fields copied verbatim from source to target rows for every
# parent doctype. Keeps the audit trail intact and makes re-runs idempotent.
PRESERVED_META_FIELDS = (
	"name",
	"owner",
	"creation",
	"modified",
	"modified_by",
	"docstatus",
)

# Optional metadata caches we copy if present on the source. _comments is
# deprecated and skipped. _assign is regenerated by Phase 4 when ToDos move
# but copying the cache here avoids a transient blank state in the desk.
PRESERVED_META_CACHE_FIELDS = (
	"_user_tags",
	"_assign",
	"_liked_by",
)

CHUNK_SIZE = 500
SAMPLE_FAILED_LIMIT = 50

# Dependency order for the orchestrator — lookups before parents so Link
# values resolve. Distinct from SOURCE_DOCTYPES (which is UI-tab order on
# the Settings form).
MIGRATION_ORDER = [
	# leaf lookups first
	"Industry Type",
	"UTM Source",
	"Opportunity Lost Reason",
	"Territory",
	"Item",
	# parents
	"Prospect",
	"Lead",
	"Opportunity",
]


# ---------------------------------------------------------------------------
# whitelisted entry points
# ---------------------------------------------------------------------------

@frappe.whitelist()
def run_migration(source_doctype: str | None = None) -> dict:
	"""Enqueue an orchestrator job. Returns the new CRM Migration Run name.

	`source_doctype = None` runs every locked source in dependency order
	(unlocked sources are refused — full-scope requires every tab locked).
	Otherwise runs just that single step, requiring its tab to be locked.
	"""
	frappe.has_permission(SETTINGS_DOCTYPE, "write", throw=True)
	frappe.has_permission(RUN_DOCTYPE, "create", throw=True)

	settings = frappe.get_single(SETTINGS_DOCTYPE)

	if source_doctype and source_doctype not in SOURCE_DOCTYPES:
		frappe.throw(
			_("Unknown source doctype: {0}").format(source_doctype),
			title=_("Bad Argument"),
		)

	if source_doctype:
		# Single-source run: only that tab needs to be locked.
		prefix = source_doctype.lower().replace(" ", "_")
		if not settings.get(f"{prefix}_locked"):
			frappe.throw(
				_("Lock the {0} mapping before running its migration.").format(source_doctype),
				title=_("Tab Not Locked"),
			)
	else:
		# Full-scope run: every tab must be locked.
		unlocked = [
			s for s in SOURCE_DOCTYPES
			if not settings.get(f"{s.lower().replace(' ', '_')}_locked")
		]
		if unlocked:
			frappe.throw(
				_("Lock every tab before running the full migration. Unlocked: {0}").format(
					", ".join(unlocked)
				),
				title=_("Tabs Not Locked"),
			)

	scope = "Single DocType" if source_doctype else "All"
	run = frappe.get_doc(
		{
			"doctype": RUN_DOCTYPE,
			"scope": scope,
			"scoped_to": source_doctype or None,
			"status": "Pending",
		}
	).insert()

	frappe.enqueue(
		"erpnext_crm_to_frappe_crm_migrator.api.runner._execute_run",
		queue="long",
		timeout=60 * 60 * 6,
		run_name=run.name,
		source_doctype=source_doctype,
	)

	return {"ok": True, "run": run.name, "scope": scope}


# ---------------------------------------------------------------------------
# orchestrator (worker side — runs in the background queue)
# ---------------------------------------------------------------------------

def _execute_run(run_name: str, source_doctype: str | None) -> None:
	"""Background worker entry point. Runs every requested step and updates
	the run log so the user can watch progress in /app/crm-migration-run.
	"""
	run = frappe.get_doc(RUN_DOCTYPE, run_name)
	run.status = "Running"
	run.started_at = now_datetime()
	run.save(ignore_permissions=True)
	frappe.db.commit()

	steps_to_run = [source_doctype] if source_doctype else list(MIGRATION_ORDER)

	any_failed = False
	any_partial = False

	for s in steps_to_run:
		# Per-step run records — gives us a simple table view of what happened.
		step = run.append(
			"steps",
			{
				"s_doctype": s,
				"t_doctype": REVERSE_DOCTYPE_MAP.get(s, ""),
				"status": "Running",
				"started_at": now_datetime(),
			},
		)
		run.save(ignore_permissions=True)
		frappe.db.commit()

		try:
			pre_block = _preflight_link_check(s)
			if pre_block:
				step.status = "Blocked"
				step.last_error = pre_block
				step.completed_at = now_datetime()
				run.save(ignore_permissions=True)
				frappe.db.commit()
				any_failed = True
				# A blocked step short-circuits the whole orchestrator only
				# when the run is full-scope and the missing prereq is
				# upstream — better to keep going for visibility, the user
				# can re-run after they fix it.
				continue

			result = _migrate_one_doctype(s)
			step.ok_count = result["ok"]
			step.skipped_count = result["skipped"]
			step.failed_count = result["failed"]
			step.child_reanchor_count = result["child_reanchored"]
			if result["last_error"]:
				step.last_error = result["last_error"][:500]
			if result["sample_failed"]:
				step.sample_failed_names = ", ".join(result["sample_failed"])

			# Phase 3 — schema reshape for this source. Items / Contacts /
			# Lost Reason for Opportunity, Contact.links for Prospect.
			reshape_result = reshape.reshape_for(s)
			step.child_ok_count = reshape_result["ok"]
			step.child_skipped_count = reshape_result["skipped"]
			step.child_failed_count = reshape_result["failed"]
			if reshape_result["last_error"]:
				# Don't trample a parent-row error if both happened.
				if not step.last_error:
					step.last_error = reshape_result["last_error"][:500]
				else:
					combined = (step.last_error + " | reshape: " + reshape_result["last_error"])[:500]
					step.last_error = combined
			if reshape_result["sample_failed"]:
				combined_names = list(filter(None, [step.sample_failed_names])) + reshape_result["sample_failed"]
				step.sample_failed_names = ", ".join(combined_names)[:1000]

			step_failed = (result["failed"] > 0) or (reshape_result["failed"] > 0)
			step_did_anything = (
				result["ok"] or result["skipped"]
				or reshape_result["ok"] or reshape_result["skipped"]
			)
			if step_failed:
				step.status = "Failed"
				any_partial = True
			elif not step_did_anything:
				step.status = "Skipped"
			else:
				step.status = "Succeeded"

			step.completed_at = now_datetime()
		except Exception as e:
			frappe.log_error(
				f"Migrator step {s} crashed",
				frappe.get_traceback(),
			)
			step.status = "Failed"
			step.failed_count = (step.failed_count or 0) + 1
			step.last_error = (str(e) or e.__class__.__name__)[:500]
			step.completed_at = now_datetime()
			any_failed = True

		run.save(ignore_permissions=True)
		frappe.db.commit()

	# Phase 4 — activity reference rewrite. Only run on full-scope runs;
	# per-source runs stay focused on that source's parent + reshape.
	if source_doctype is None:
		any_phase4_failed, any_phase4_partial = _run_activity_phase(run)
		any_failed = any_failed or any_phase4_failed
		any_partial = any_partial or any_phase4_partial

	run.completed_at = now_datetime()
	if any_failed:
		run.status = "Failed"
	elif any_partial:
		run.status = "Partial"
	else:
		run.status = "Succeeded"
	run.save(ignore_permissions=True)
	frappe.db.commit()


# ---------------------------------------------------------------------------
# Phase 4 — activity reference rewrite (called from the orchestrator)
# ---------------------------------------------------------------------------

def _run_activity_phase(run) -> tuple[bool, bool]:
	"""Append one CRM Migration Run Step row per activity doctype.

	Returns (any_failed, any_partial) so the caller can roll the overall
	run status forward.
	"""
	any_failed = False
	any_partial = False

	for activity_dt, result in activity.rewrite_all_activities():
		step = run.append(
			"steps",
			{
				"s_doctype": activity_dt,
				"t_doctype": activity_dt,
				"status": "Running",
				"started_at": now_datetime(),
			},
		)
		step.ok_count = result["ok"]
		step.skipped_count = result["skipped"]
		step.failed_count = result["failed"]
		if result["last_error"]:
			step.last_error = result["last_error"][:500]
		if result["sample_failed"]:
			step.sample_failed_names = ", ".join(result["sample_failed"])[:1000]

		if result["failed"] > 0:
			step.status = "Failed"
			any_failed = True
		elif result["ok"] == 0:
			# No rows actually rewritten — every pair either had 0 source
			# rows or was already done in a previous run.
			step.status = "Skipped"
		else:
			step.status = "Succeeded"
		step.completed_at = now_datetime()

	run.save(ignore_permissions=True)
	frappe.db.commit()
	return any_failed, any_partial


@frappe.whitelist()
def default_setup_and_run() -> dict:
	"""One-click default migration:

	1. Refresh diff for every unlocked tab (rebuilds the editable table
	   with the current source meta).
	2. Mark every blank-action row in every unlocked tab as Skip.
	3. Lock every unlocked tab into CRM Migration Field Map.
	4. Enqueue a full-scope migration run (all 8 source steps + activity
	   rewrite).

	Tabs that are already locked are preserved untouched. Useful for
	users who want sane defaults without per-row review.
	"""
	from erpnext_crm_to_frappe_crm_migrator.api.mapping import (
		_settings_field_prefix,
		lock_doctype,
		mark_all_as_skip,
		refresh_diff,
	)

	frappe.has_permission(SETTINGS_DOCTYPE, "write", throw=True)
	frappe.has_permission(RUN_DOCTYPE, "create", throw=True)

	# Step 1: refresh
	refresh_diff()

	# Step 2 + 3: per-tab skip-blanks then lock, only on unlocked tabs.
	settings = frappe.get_single(SETTINGS_DOCTYPE)
	locked_now = 0
	already_locked = 0
	for s in SOURCE_DOCTYPES:
		prefix = _settings_field_prefix(s)
		# Re-read each loop in case lock_doctype mutated state
		settings.reload()
		if settings.get(f"{prefix}_locked"):
			already_locked += 1
			continue
		mark_all_as_skip(s)
		lock_doctype(s)
		locked_now += 1

	# Step 4: full-scope migration (this also runs Phase 4 activity)
	run_result = run_migration(source_doctype=None)

	return {
		"ok": True,
		"locked_now": locked_now,
		"already_locked": already_locked,
		"run": run_result.get("run"),
	}


@frappe.whitelist()
def run_activity_only() -> dict:
	"""Whitelisted entry for the standalone 'Migrate Activity Records'
	button. Enqueues a Run that only does Phase 4. Requires every tab
	to be locked so the activity rewrite has consistent target names
	across all source doctypes.
	"""
	frappe.has_permission(SETTINGS_DOCTYPE, "write", throw=True)
	frappe.has_permission(RUN_DOCTYPE, "create", throw=True)

	settings = frappe.get_single(SETTINGS_DOCTYPE)
	unlocked = [
		s for s in SOURCE_DOCTYPES
		if not settings.get(f"{s.lower().replace(' ', '_')}_locked")
	]
	if unlocked:
		frappe.throw(
			_("Lock every tab before rewriting activity references. Unlocked: {0}").format(
				", ".join(unlocked)
			),
			title=_("Tabs Not Locked"),
		)

	run = frappe.get_doc(
		{
			"doctype": RUN_DOCTYPE,
			"scope": "Single DocType",
			"scoped_to": None,
			"status": "Pending",
		}
	).insert()

	frappe.enqueue(
		"erpnext_crm_to_frappe_crm_migrator.api.runner._execute_activity_run",
		queue="long",
		timeout=60 * 60,
		run_name=run.name,
	)

	return {"ok": True, "run": run.name}


def _execute_activity_run(run_name: str) -> None:
	"""Background worker for run_activity_only — runs only Phase 4."""
	run = frappe.get_doc(RUN_DOCTYPE, run_name)
	run.status = "Running"
	run.started_at = now_datetime()
	run.save(ignore_permissions=True)
	frappe.db.commit()

	any_failed, any_partial = _run_activity_phase(run)

	run.completed_at = now_datetime()
	if any_failed:
		run.status = "Failed"
	elif any_partial:
		run.status = "Partial"
	else:
		run.status = "Succeeded"
	run.save(ignore_permissions=True)
	frappe.db.commit()


# ---------------------------------------------------------------------------
# Customer → Prospect bridge for Opportunity-from-Customer rows
# ---------------------------------------------------------------------------

def _ensure_customer_prospects(source_doctype: str) -> dict[str, str]:
	"""For Opportunity rows where `opportunity_from = 'Customer'`, ensure
	a Prospect exists for each referenced Customer (creating one from
	Customer data if missing). Also creates the matching CRM Organization
	since the Prospect step has already run by the time we reach
	Opportunity in the dependency order.

	Returns `{customer_name: prospect_name}` — the chunk loop rewrites
	`Opportunity.party_name` from Customer.name to Prospect.name so the
	dynamic-link routing writes a valid Organization reference on
	CRM Deal.
	"""
	if source_doctype != "Opportunity":
		return {}
	if not frappe.db.exists("DocType", "Customer"):
		return {}

	customer_ids = frappe.db.sql_list(
		"""
		SELECT DISTINCT party_name FROM `tabOpportunity`
		WHERE opportunity_from = 'Customer' AND party_name IS NOT NULL AND party_name != ''
		"""
	)
	if not customer_ids:
		return {}

	customers = frappe.db.sql(
		"""
		SELECT name, customer_name, owner, creation, modified, modified_by
		FROM `tabCustomer`
		WHERE name IN %(ids)s
		""",
		{"ids": tuple(customer_ids)},
		as_dict=True,
	)
	if not customers:
		return {}

	existing_prospects = set(frappe.db.sql_list("SELECT name FROM `tabProspect`"))
	existing_orgs = set(frappe.db.sql_list("SELECT name FROM `tabCRM Organization`"))

	translation: dict[str, str] = {}
	prospects_to_insert: list[tuple] = []
	orgs_to_insert: list[tuple] = []

	for cust in customers:
		# Prospect.autoname = field:company_name → name = company_name.
		# Prefer the human-readable customer_name; fall back to Customer.name
		# if the field is empty so a CRM Organization always lands.
		prospect_name = cust["customer_name"] or cust["name"]
		translation[cust["name"]] = prospect_name

		if prospect_name not in existing_prospects:
			prospects_to_insert.append((
				prospect_name,
				cust["owner"],
				cust["creation"],
				cust["modified"],
				cust["modified_by"],
				0,
				prospect_name,
			))
			existing_prospects.add(prospect_name)

		if prospect_name not in existing_orgs:
			orgs_to_insert.append((
				prospect_name,
				cust["owner"],
				cust["creation"],
				cust["modified"],
				cust["modified_by"],
				0,
				prospect_name,
			))
			existing_orgs.add(prospect_name)

	if prospects_to_insert:
		frappe.db.bulk_insert(
			"Prospect",
			fields=[
				"name", "owner", "creation", "modified", "modified_by",
				"docstatus", "company_name",
			],
			values=prospects_to_insert,
			ignore_duplicates=True,
		)
	if orgs_to_insert:
		frappe.db.bulk_insert(
			"CRM Organization",
			fields=[
				"name", "owner", "creation", "modified", "modified_by",
				"docstatus", "organization_name",
			],
			values=orgs_to_insert,
			ignore_duplicates=True,
		)

	frappe.db.commit()
	return translation


# ---------------------------------------------------------------------------
# per-doctype migration step
# ---------------------------------------------------------------------------

def _migrate_one_doctype(source_doctype: str) -> dict:
	"""Migrate every row of one source doctype into its target.

	Returns a dict with ok/skipped/failed counts plus a sample of failed
	source-names and the most recent error message.
	"""
	target_doctype = REVERSE_DOCTYPE_MAP.get(source_doctype, "")
	if not target_doctype:
		return {
			"ok": 0,
			"skipped": 0,
			"failed": 0,
			"child_reanchored": 0,
			"last_error": "",
			"sample_failed": [],
		}

	field_pairs = _load_field_map(source_doctype, target_doctype)
	if not field_pairs:
		return {
			"ok": 0,
			"skipped": 0,
			"failed": 0,
			"child_reanchored": 0,
			"last_error": "",
			"sample_failed": [],
		}

	target_meta = frappe.get_meta(target_doctype)

	# Build the column list we'll bulk-insert. Order matters — bulk_insert
	# expects the values tuples to match this sequence exactly.
	target_cols: list[str] = []
	for f in PRESERVED_META_FIELDS:
		target_cols.append(f)
	for f in PRESERVED_META_CACHE_FIELDS:
		# include only if the target table actually has the column
		if target_meta.has_field(f) or _column_exists(target_doctype, f):
			target_cols.append(f)

	# Skip Table-type target fields — we don't bulk-insert child tables this
	# way. The child re-anchor step handles shared-schema children, and
	# Phase 3 handles schema-reshape children.
	mapped_cols: list[str] = []
	for _src, tgt in field_pairs:
		tgt_df = target_meta.get_field(tgt)
		if tgt_df is None:
			continue
		if tgt_df.fieldtype in ("Table", "Table MultiSelect"):
			continue
		mapped_cols.append(tgt)

	# Ensure each mapped column is unique and not already in target_cols.
	for c in mapped_cols:
		if c not in target_cols:
			target_cols.append(c)

	# Add naming_series with empty default if the target requires it but the
	# source doesn't carry it. We keep the source `name`, so naming_series
	# being '' is fine — name is already set explicitly.
	if target_meta.has_field("naming_series") and "naming_series" not in target_cols:
		target_cols.append("naming_series")

	# Dynamic-Link source fields (e.g. Opportunity.party_name) route to
	# different target columns at write time. Make sure every column the
	# router could touch is in the column set so values aren't dropped
	# during the tuple build in _build_target_row.
	for (src_dt, _src_field), rule in DYNAMIC_LINK_ROUTES.items():
		if src_dt != source_doctype:
			continue
		for tgt_col in (*rule["routes"].values(), rule["default_target"]):
			if tgt_col not in target_cols and target_meta.has_field(tgt_col):
				target_cols.append(tgt_col)

	# A reverse map src→tgt (for this doctype only) used during preprocess.
	src_to_tgt = {src: tgt for src, tgt in field_pairs}

	# Customer-from Opportunity bridge: ensure Prospect + CRM Organization
	# exist for every Customer referenced by an Opportunity. Returns a
	# translation map used in the chunk loop to rewrite party_name from
	# Customer.name to Prospect.name (= Customer.customer_name).
	customer_to_prospect = _ensure_customer_prospects(source_doctype)

	# Read source rows in chunks via raw SQL — guarantees we see every
	# column (including `_user_tags`, `_assign`, etc.) regardless of
	# get_all's defaults.
	total = frappe.db.count(source_doctype)

	ok = 0
	failed = 0
	skipped = 0
	last_error = ""
	sample_failed: list[str] = []
	offset = 0

	while offset < total:
		try:
			rows = frappe.db.sql(
				f"SELECT * FROM `tab{source_doctype}` ORDER BY `name` LIMIT %s OFFSET %s",
				(CHUNK_SIZE, offset),
				as_dict=True,
			)
		except Exception as e:
			last_error = f"chunk read at offset {offset}: {e}"
			break
		if not rows:
			break

		values: list[tuple] = []
		for src_row in rows:
			try:
				# Customer-from Opportunity: rewrite party_name to the
				# Prospect name that _ensure_customer_prospects materialised
				# so the dynamic-link routing writes a valid Organization
				# reference on CRM Deal.
				if (
					customer_to_prospect
					and src_row.get("opportunity_from") == "Customer"
				):
					translated = customer_to_prospect.get(src_row.get("party_name"))
					if translated:
						src_row["party_name"] = translated

				out = _build_target_row(
					src_row,
					src_to_tgt,
					target_cols,
					target_doctype,
					source_doctype,
				)
				values.append(out)
			except Exception as e:
				failed += 1
				last_error = str(e)[:500]
				if len(sample_failed) < SAMPLE_FAILED_LIMIT:
					sample_failed.append(src_row.get("name") or "<unknown>")

		if values:
			# Determine which names in this batch already exist, BEFORE the
			# insert — that's our skipped count for this chunk. Anything
			# else is genuinely new.
			batch_names = [v[0] for v in values]
			pre_existing = (
				set(
					frappe.db.sql_list(
						f"SELECT `name` FROM `tab{target_doctype}` WHERE `name` IN %s",
						(tuple(batch_names),),
					)
				)
				if batch_names
				else set()
			)
			try:
				frappe.db.bulk_insert(
					target_doctype,
					fields=target_cols,
					values=values,
					ignore_duplicates=True,
				)
				ok += len(values) - len(pre_existing)
				skipped += len(pre_existing)
			except Exception as e:
				# Whole-chunk failure (rare — usually a schema mismatch).
				# Mark every row in the chunk as failed; the user will see
				# the error in last_error.
				failed += len(values)
				last_error = f"bulk_insert chunk at offset {offset}: {e}"
				for v in values[:SAMPLE_FAILED_LIMIT - len(sample_failed)]:
					sample_failed.append(v[0])  # name is column 0

		frappe.db.commit()
		offset += CHUNK_SIZE

	# Re-anchor shared-schema child rows (e.g. tabCRM Status Change Log)
	# via meta inspection — Table fields don't appear in the locked
	# field map anymore, so we discover them by walking source meta.
	child_reanchored = _reanchor_shared_children(
		source_doctype, target_doctype, target_meta
	)

	return {
		"ok": ok,
		"skipped": skipped,
		"failed": failed,
		"child_reanchored": child_reanchored,
		"last_error": last_error,
		"sample_failed": sample_failed,
	}


# ---------------------------------------------------------------------------
# preprocessing
# ---------------------------------------------------------------------------

def _build_target_row(
	src_row: dict,
	src_to_tgt: dict,
	target_cols: list[str],
	target_doctype: str,
	source_doctype: str,
) -> tuple:
	"""Compute a tuple of values matching `target_cols` order for one row."""
	out: dict[str, object] = {}

	# 1. preserved meta — copied straight from source
	for f in PRESERVED_META_FIELDS:
		out[f] = src_row.get(f)

	# 2. metadata caches — copied if source has them (target column membership
	# was already enforced when target_cols was built)
	for f in PRESERVED_META_CACHE_FIELDS:
		if f in target_cols:
			out[f] = src_row.get(f)

	# 3. mapped fields — the locked map drives the renames. Dynamic
	# Link source fields are deliberately skipped here so they don't
	# fight other source fields that legitimately map to the same
	# target column (e.g. a custom field on Opportunity → CRM Deal
	# organization). Step 5 is the sole writer for dynamic-link
	# values.
	dynamic_sources = {
		src_field
		for (src_dt, src_field) in DYNAMIC_LINK_ROUTES
		if src_dt == source_doctype
	}
	for src, tgt in src_to_tgt.items():
		if src in dynamic_sources:
			continue
		if tgt not in target_cols:
			continue
		out[tgt] = src_row.get(src)

	# 4. naming_series default — we provided `name` explicitly, so this is
	# just here to satisfy NOT NULL on targets that have the column.
	if "naming_series" in target_cols and not out.get("naming_series"):
		out["naming_series"] = src_row.get("naming_series") or ""

	# 5. Dynamic-Link routing — write the source value into the column
	# chosen by the controller field (e.g. Opportunity's party_name
	# lands on CRM Deal.lead when opportunity_from='Lead' and on
	# CRM Deal.organization when ='Prospect'). The other rule columns
	# are left with whatever step 3 wrote — so a custom field that
	# maps to organization survives in the from='Lead' case.
	for (src_dt, src_field), rule in DYNAMIC_LINK_ROUTES.items():
		if src_dt != source_doctype:
			continue
		controller_value = src_row.get(rule["controller_field"])
		value = src_row.get(src_field)
		chosen = rule["routes"].get(controller_value, rule["default_target"])
		if chosen in target_cols and value:
			out[chosen] = value

	# Build the tuple in target_cols order. None for any column we didn't
	# populate — the database default takes over (typically NULL).
	return tuple(out.get(c) for c in target_cols)


def _load_field_map(source_doctype: str, target_doctype: str) -> list[tuple[str, str]]:
	"""Return [(source_field, target_field), ...] from the locked Field Map.

	Skips meta fields (handled separately by PRESERVED_META_FIELDS).
	"""
	rows = frappe.db.sql(
		f"""
		SELECT `source`, `target`
		FROM `tab{FIELD_MAP_DOCTYPE}`
		WHERE s_doctype = %s AND t_doctype = %s
		""",
		(source_doctype, target_doctype),
		as_dict=True,
	)
	pairs: list[tuple[str, str]] = []
	for r in rows:
		if r["source"] in PRESERVED_META_FIELDS:
			continue
		pairs.append((r["source"], r["target"]))
	return pairs


def _column_exists(doctype: str, column: str) -> bool:
	"""Return True if `tab<doctype>` has a column named `column`."""
	try:
		cols = frappe.db.get_table_columns(doctype)
		return column in cols
	except Exception:
		return False


# ---------------------------------------------------------------------------
# child-row re-anchoring (shared-schema only)
# ---------------------------------------------------------------------------

def _reanchor_shared_children(
	source_doctype: str,
	target_doctype: str,
	target_meta,
) -> int:
	"""Rewrite parenttype/parentfield on child rows whose child doctype is
	identical on both source and target meta.

	Discovery is via meta inspection — we don't read the locked field
	map for this. Table fields are deliberately hidden from the diff
	UI (they aren't column-mapped); shared-schema Tables still need
	re-anchoring, so we walk source meta and match every Table field
	whose name + options align with a Table on target meta. Schema-
	reshape children (where the child doctype itself changes) are
	Phase 3 territory and never enter this loop.

	Returns the total number of child rows updated across all eligible
	child doctypes.
	"""
	source_meta = frappe.get_meta(source_doctype)
	total = 0
	seen: set[tuple[str, str]] = set()

	for src_df in source_meta.fields:
		if src_df.fieldtype not in ("Table", "Table MultiSelect"):
			continue
		if not src_df.options:
			continue
		# Match a same-name Table field on target with same child doctype.
		tgt_df = target_meta.get_field(src_df.fieldname)
		if tgt_df is None or tgt_df.fieldtype != src_df.fieldtype:
			continue
		if (tgt_df.options or "") != (src_df.options or ""):
			# different child doctype → schema reshape, Phase 3
			continue
		child_dt = src_df.options
		src_field = src_df.fieldname
		tgt_field = src_df.fieldname  # same name

		key = (child_dt, src_field)
		if key in seen:
			continue
		seen.add(key)

		# Count rows that still need re-anchoring BEFORE the UPDATE — that
		# count IS the number we'll be moving. Re-runs see 0 here because
		# the previous run already moved them all to the target parenttype.
		to_move = frappe.db.count(
			child_dt,
			filters={
				"parenttype": source_doctype,
				"parentfield": src_field,
			},
		)
		if to_move:
			frappe.db.sql(
				f"""
				UPDATE `tab{child_dt}`
				SET parenttype = %s,
				    parentfield = %s
				WHERE parenttype = %s
				  AND parentfield = %s
				""",
				(target_doctype, tgt_field, source_doctype, src_field),
			)
			total += int(to_move)

	frappe.db.commit()
	return total


# ---------------------------------------------------------------------------
# pre-flight: verify upstream lookups exist before migrating a parent
# ---------------------------------------------------------------------------

# Each parent maps to the upstream lookup target doctypes whose Link values
# may appear on its rows. Computed from the registry: for every parent's
# Link field whose target options is one of our migration target lookup
# doctypes, that target needs to be populated before this parent runs.
_PARENT_DEPENDENCIES = {
	"Lead": ["CRM Industry", "CRM Territory", "CRM Lead Source"],
	"Opportunity": [
		"CRM Industry",
		"CRM Territory",
		"CRM Lead Source",
		"CRM Lost Reason",
		"CRM Organization",  # party_name → Prospect → CRM Organization
	],
	"Prospect": ["CRM Industry", "CRM Territory"],
	# Self-references aren't pre-checked — the bulk_insert handles the same
	# table fine regardless of order, and Frappe Link fields aren't FK-enforced.
	"Territory": [],
	"Item": [],
	"Industry Type": [],
	"UTM Source": [],
	"Opportunity Lost Reason": [],
}


def _preflight_link_check(source_doctype: str) -> str | None:
	"""Return an explanatory string if the parent can't run yet, else None.

	A parent step is blocked if any of its upstream CRM lookup tables is
	empty when the source has Link values pointing into the corresponding
	source-side lookup. The check is deliberately coarse — empty target
	table is the failure mode we care about; row-by-row mismatches are
	caught later by the bulk_insert path.
	"""
	deps = _PARENT_DEPENDENCIES.get(source_doctype, [])
	missing: list[str] = []
	for target_lookup in deps:
		try:
			n = frappe.db.count(target_lookup)
		except Exception:
			n = 0
		if n == 0:
			# Distinguish "target table empty because nothing migrated yet"
			# from "no source rows reference this lookup at all". Cheap
			# heuristic: if the source-side equivalent has rows, this is a
			# real prereq miss.
			source_lookup = _crm_to_source_doctype(target_lookup)
			if source_lookup:
				try:
					src_n = frappe.db.count(source_lookup)
				except Exception:
					src_n = 0
				if src_n > 0:
					missing.append(target_lookup)

	if missing:
		return (
			f"Upstream lookups not yet migrated: {', '.join(missing)}. "
			f"Run the per-tab migration for those source doctypes first, "
			f"or use the top-level Run Migration button to migrate all."
		)
	return None


def _crm_to_source_doctype(crm_doctype: str) -> str | None:
	"""Reverse-lookup helper for _preflight_link_check.

	REVERSE_DOCTYPE_MAP is keyed by ERPNext source name and yields the CRM
	target name. We need the inverse: given a CRM target, what's its
	ERPNext source?
	"""
	for src, tgt in REVERSE_DOCTYPE_MAP.items():
		if tgt == crm_doctype:
			return src
	return None
