"""Core records migration runner — copies rows from each source doctype
to its target via `frappe.db.bulk_insert`, preserving source meta.

See `docs/architecture.md` for the step pipeline and
`docs/decisions.md` for the source-meta / bulk_insert rationale.
"""

from __future__ import annotations

import frappe
from frappe import _
from frappe.utils import now_datetime

from erpnext_crm_to_frappe_crm_migrator.api import activity, reshape
from erpnext_crm_to_frappe_crm_migrator.api.mapping import DYNAMIC_LINK_ROUTES
from erpnext_crm_to_frappe_crm_migrator.mapping.registry import (
	REVERSE_DOCTYPE_MAP,
	SOURCE_DOCTYPES,
	SUGGESTION_MAP,
)

SETTINGS_DOCTYPE = "CRM Migration Settings"
FIELD_MAP_DOCTYPE = "CRM Migration Field Map"
RUN_DOCTYPE = "CRM Migration Run"

# Source-meta fields copied verbatim from source to target rows for every
# parent doctype. Keeps the audit trail intact and makes re-runs idempotent.
PRESERVED_META_FIELDS = (
	"name",
	"owner",
	"creation",
	"modified",
	"modified_by",
	"docstatus",
)

# Optional metadata caches we copy if present on the source. _comments is
# deprecated and skipped. _assign is regenerated by reshape_assignments when ToDos move
# but copying the cache here avoids a transient blank state in the desk.
PRESERVED_META_CACHE_FIELDS = (
	"_user_tags",
	"_assign",
	"_liked_by",
)

CHUNK_SIZE = 500
SAMPLE_FAILED_LIMIT = 50

# Dependency order for the orchestrator — lookups before parents so Link
# values resolve. Distinct from SOURCE_DOCTYPES (which is UI-tab order on
# the Settings form).
MIGRATION_ORDER = [
	# leaf lookups first
	"Industry Type",
	"UTM Source",
	"Opportunity Lost Reason",
	"Territory",
	"Item",
	# parents
	"Prospect",
	"Lead",
	"Opportunity",
]


# ---------------------------------------------------------------------------
# whitelisted entry points
# ---------------------------------------------------------------------------


@frappe.whitelist()
def run_migration(source_doctype: str | None = None) -> dict:
	"""Enqueue an orchestrator job. Returns the new CRM Migration Run name.

	`source_doctype = None` runs every locked source in dependency order
	(unlocked sources are refused — full-scope requires every tab locked).
	Otherwise runs just that single step, requiring its tab to be locked.
	"""
	frappe.has_permission(SETTINGS_DOCTYPE, "write", throw=True)
	frappe.has_permission(RUN_DOCTYPE, "create", throw=True)

	settings = frappe.get_single(SETTINGS_DOCTYPE)

	if source_doctype and source_doctype not in SOURCE_DOCTYPES:
		frappe.throw(
			_("Unknown source doctype: {0}").format(source_doctype),
			title=_("Bad Argument"),
		)

	if source_doctype:
		# Single-source run: only that tab needs to be locked.
		prefix = source_doctype.lower().replace(" ", "_")
		if not settings.get(f"{prefix}_locked"):
			frappe.throw(
				_("Lock the {0} mapping before running its migration.").format(source_doctype),
				title=_("Tab Not Locked"),
			)
	else:
		# Full-scope run: every tab must be locked.
		unlocked = [s for s in SOURCE_DOCTYPES if not settings.get(f"{s.lower().replace(' ', '_')}_locked")]
		if unlocked:
			frappe.throw(
				_("Lock every tab before running the full migration. Unlocked: {0}").format(
					", ".join(unlocked)
				),
				title=_("Tabs Not Locked"),
			)

	scope = "Single DocType" if source_doctype else "All"
	run = frappe.get_doc(
		{
			"doctype": RUN_DOCTYPE,
			"scope": scope,
			"scoped_to": source_doctype or None,
			"status": "Pending",
		}
	).insert()

	frappe.enqueue(
		"erpnext_crm_to_frappe_crm_migrator.api.runner._execute_run",
		queue="long",
		timeout=60 * 60 * 6,
		run_name=run.name,
		source_doctype=source_doctype,
	)

	return {"ok": True, "run": run.name, "scope": scope}


# ---------------------------------------------------------------------------
# orchestrator (worker side — runs in the background queue)
# ---------------------------------------------------------------------------


def _execute_run(run_name: str, source_doctype: str | None) -> None:
	"""Background worker entry point. Runs every requested step and updates
	the run log so the user can watch progress in /app/crm-migration-run.
	"""
	run = frappe.get_doc(RUN_DOCTYPE, run_name)
	run.status = "Running"
	run.started_at = now_datetime()
	run.save(ignore_permissions=True)
	frappe.db.commit()  # nosemgrep: frappe-manual-commit -- live progress — show "Running" in /app/crm-migration-run before the first step starts

	steps_to_run = [source_doctype] if source_doctype else list(MIGRATION_ORDER)

	any_failed = False
	any_partial = False

	for s in steps_to_run:
		# Per-step run records — gives us a simple table view of what happened.
		step = run.append(
			"steps",
			{
				"s_doctype": s,
				"t_doctype": REVERSE_DOCTYPE_MAP.get(s, ""),
				"status": "Running",
				"started_at": now_datetime(),
			},
		)
		run.save(ignore_permissions=True)
		frappe.db.commit()  # nosemgrep: frappe-manual-commit -- live progress — show this step as Running while it executes

		try:
			pre_block = _preflight_link_check(s)
			if pre_block:
				step.status = "Blocked"
				step.last_error = pre_block
				step.completed_at = now_datetime()
				run.save(ignore_permissions=True)
				frappe.db.commit()  # nosemgrep: frappe-manual-commit -- live progress — surface Blocked status the moment preflight fails
				any_failed = True
				# A blocked step short-circuits the whole orchestrator only
				# when the run is full-scope and the missing prereq is
				# upstream — better to keep going for visibility, the user
				# can re-run after they fix it.
				continue

			result = _migrate_one_doctype(s)
			step.ok_count = result["ok"]
			step.skipped_count = result["skipped"]
			step.failed_count = result["failed"]
			step.child_reanchor_count = result["child_reanchored"]
			if result["last_error"]:
				step.last_error = result["last_error"][:500]
			if result["sample_failed"]:
				step.sample_failed_names = ", ".join(result["sample_failed"])

			# Schema reshape for this source. Items / Contacts /
			# Lost Reason for Opportunity, Contact.links for Prospect.
			reshape_result = reshape.reshape_for(s)
			step.child_ok_count = reshape_result["ok"]
			step.child_skipped_count = reshape_result["skipped"]
			step.child_failed_count = reshape_result["failed"]
			if reshape_result["last_error"]:
				# Don't trample a parent-row error if both happened.
				if not step.last_error:
					step.last_error = reshape_result["last_error"][:500]
				else:
					combined = (step.last_error + " | reshape: " + reshape_result["last_error"])[:500]
					step.last_error = combined
			if reshape_result["sample_failed"]:
				prior = [step.sample_failed_names] if step.sample_failed_names else []
				combined_names = prior + reshape_result["sample_failed"]
				step.sample_failed_names = ", ".join(combined_names)[:1000]

			step_failed = (result["failed"] > 0) or (reshape_result["failed"] > 0)
			step_did_anything = (
				result["ok"] or result["skipped"] or reshape_result["ok"] or reshape_result["skipped"]
			)
			if step_failed:
				step.status = "Failed"
				any_partial = True
			elif not step_did_anything:
				step.status = "Skipped"
			else:
				step.status = "Succeeded"

			step.completed_at = now_datetime()
		except Exception as e:
			frappe.log_error(
				f"Migrator step {s} crashed",
				frappe.get_traceback(),
			)
			step.status = "Failed"
			step.failed_count = (step.failed_count or 0) + 1
			step.last_error = (str(e) or e.__class__.__name__)[:500]
			step.completed_at = now_datetime()
			any_failed = True

		run.save(ignore_permissions=True)
		frappe.db.commit()  # nosemgrep: frappe-manual-commit -- live progress — surface per-step final status as each step ends

	# Activity reference rewrite. Only run on full-scope runs;
	# per-source runs stay focused on that source's parent + reshape.
	if source_doctype is None:
		any_phase4_failed, any_phase4_partial = _run_activity_phase(run)
		any_failed = any_failed or any_phase4_failed
		any_partial = any_partial or any_phase4_partial

	run.completed_at = now_datetime()
	if any_failed:
		run.status = "Failed"
	elif any_partial:
		run.status = "Partial"
	else:
		run.status = "Succeeded"
	run.save(ignore_permissions=True)
	frappe.db.commit()  # nosemgrep: frappe-manual-commit -- live progress — final overall run status visible in the desk


# ---------------------------------------------------------------------------
# Activity reference rewrite (called from the orchestrator)
# ---------------------------------------------------------------------------


def _run_activity_phase(run) -> tuple[bool, bool]:
	"""Append one CRM Migration Run Step row per activity doctype.

	Returns (any_failed, any_partial) so the caller can roll the overall
	run status forward.
	"""
	any_failed = False
	any_partial = False

	for activity_dt, result in activity.rewrite_all_activities():
		step = run.append(
			"steps",
			{
				"s_doctype": activity_dt,
				"t_doctype": activity_dt,
				"status": "Running",
				"started_at": now_datetime(),
			},
		)
		step.ok_count = result["ok"]
		step.skipped_count = result["skipped"]
		step.failed_count = result["failed"]
		if result["last_error"]:
			step.last_error = result["last_error"][:500]
		if result["sample_failed"]:
			step.sample_failed_names = ", ".join(result["sample_failed"])[:1000]

		if result["failed"] > 0:
			step.status = "Failed"
			any_failed = True
		elif result["ok"] == 0 and result["skipped"] == 0:
			# Nothing was evaluated at all — usually means the activity
			# doctype isn't installed on this site.
			step.status = "Skipped"
		else:
			# Either rewrote rows, OR evaluated every source pair and
			# found nothing to rewrite (idempotent re-run, or no
			# activity records ever pointed at the source doctypes).
			# Both are success.
			step.status = "Succeeded"
		step.completed_at = now_datetime()

	run.save(ignore_permissions=True)
	frappe.db.commit()  # nosemgrep: frappe-manual-commit -- live progress — activity-phase step rows visible in the desk
	return any_failed, any_partial


@frappe.whitelist()
def default_setup_and_run() -> dict:
	"""One-click default migration:

	1. Refresh diff for every unlocked tab (rebuilds the editable table
	   with the current source meta).
	2. Mark every blank-action row in every unlocked tab as Skip.
	3. Lock every unlocked tab into CRM Migration Field Map.
	4. Enqueue a full-scope migration run (all 8 source steps + activity
	   rewrite).

	Tabs that are already locked are preserved untouched. Useful for
	users who want sane defaults without per-row review.
	"""
	from erpnext_crm_to_frappe_crm_migrator.api.mapping import (
		_settings_field_prefix,
		lock_doctype,
		mark_all_as_skip,
		refresh_diff,
	)

	frappe.has_permission(SETTINGS_DOCTYPE, "write", throw=True)
	frappe.has_permission(RUN_DOCTYPE, "create", throw=True)

	# Step 1: refresh
	refresh_diff()

	# Step 2 + 3: per-tab skip-blanks then lock, only on unlocked tabs.
	settings = frappe.get_single(SETTINGS_DOCTYPE)
	locked_now = 0
	already_locked = 0
	for s in SOURCE_DOCTYPES:
		prefix = _settings_field_prefix(s)
		# Re-read each loop in case lock_doctype mutated state
		settings.reload()
		if settings.get(f"{prefix}_locked"):
			already_locked += 1
			continue
		mark_all_as_skip(s)
		lock_doctype(s)
		locked_now += 1

	# Step 4: full-scope migration (this also runs the activity rewrite)
	run_result = run_migration(source_doctype=None)

	return {
		"ok": True,
		"locked_now": locked_now,
		"already_locked": already_locked,
		"run": run_result.get("run"),
	}


@frappe.whitelist()
def run_activity_only() -> dict:
	"""Whitelisted entry for the standalone 'Migrate Activity Records'
	button. Enqueues a Run that only does the activity rewrite. Requires every tab
	to be locked so the activity rewrite has consistent target names
	across all source doctypes.
	"""
	frappe.has_permission(SETTINGS_DOCTYPE, "write", throw=True)
	frappe.has_permission(RUN_DOCTYPE, "create", throw=True)

	settings = frappe.get_single(SETTINGS_DOCTYPE)
	unlocked = [s for s in SOURCE_DOCTYPES if not settings.get(f"{s.lower().replace(' ', '_')}_locked")]
	if unlocked:
		frappe.throw(
			_("Lock every tab before rewriting activity references. Unlocked: {0}").format(
				", ".join(unlocked)
			),
			title=_("Tabs Not Locked"),
		)

	run = frappe.get_doc(
		{
			"doctype": RUN_DOCTYPE,
			"scope": "Single DocType",
			"scoped_to": None,
			"status": "Pending",
		}
	).insert()

	frappe.enqueue(
		"erpnext_crm_to_frappe_crm_migrator.api.runner._execute_activity_run",
		queue="long",
		timeout=60 * 60,
		run_name=run.name,
	)

	return {"ok": True, "run": run.name}


def _execute_activity_run(run_name: str) -> None:
	"""Background worker for run_activity_only — runs only the activity rewrite."""
	run = frappe.get_doc(RUN_DOCTYPE, run_name)
	run.status = "Running"
	run.started_at = now_datetime()
	run.save(ignore_permissions=True)
	frappe.db.commit()  # nosemgrep: frappe-manual-commit -- live progress — show activity-only run as Running before it starts

	any_failed, any_partial = _run_activity_phase(run)

	run.completed_at = now_datetime()
	if any_failed:
		run.status = "Failed"
	elif any_partial:
		run.status = "Partial"
	else:
		run.status = "Succeeded"
	run.save(ignore_permissions=True)
	frappe.db.commit()  # nosemgrep: frappe-manual-commit -- live progress — final activity-only run status visible in the desk


# ---------------------------------------------------------------------------
# Lead → Prospect lookup for Opportunity-from-Lead rows
# ---------------------------------------------------------------------------


def _build_lead_to_prospect_map(source_doctype: str) -> dict[str, str]:
	"""Return `{lead_name: prospect_name}` for the Opportunity step.

	When an Opportunity is `opportunity_from='Lead'`, the dynamic-link
	rule writes `party_name` to `CRM Deal.lead` — but the deal's
	organization context is the Prospect that owns the Lead. ERPNext
	stores that link on Prospect's `leads` child table (each row has
	`parent = Prospect.name`, `lead = Lead.name`). We invert the table
	once per step and use it during preprocess to populate
	`CRM Deal.organization` from the Lead's owning Prospect.
	"""
	if source_doctype != "Opportunity":
		return {}
	if not frappe.db.exists("DocType", "Prospect Lead"):
		return {}
	pl = frappe.qb.DocType("Prospect Lead")
	rows = (
		frappe.qb.from_(pl)
		.select(pl.lead, pl.parent)
		.where((pl.parenttype == "Prospect") & pl.lead.isnotnull() & (pl.lead != ""))
	).run(as_dict=True)
	# If a Lead appears under multiple Prospects, the last one wins —
	# inversions of one-to-many usually pick last; the user can fix
	# specific rows post-migration if a different choice is desired.
	return {r["lead"]: r["parent"] for r in rows}


def _ensure_lead_company_orgs(
	source_doctype: str,
	lead_to_prospect: dict[str, str],
) -> dict[str, str]:
	"""Fallback for Opportunities-from-Lead whose Lead has no owning
	Prospect: use the Lead's own `company_name` as the organization.

	Returns `{lead_name: company_name}` and lazy-creates a CRM
	Organization row per distinct company_name so `CRM Deal.organization`
	resolves to a real row. Without this, `CRM Deal.title_field =
	'organization'` renders as "undefined" on the desk for these deals.
	"""
	if source_doctype != "Opportunity":
		return {}
	if not frappe.db.exists("DocType", "CRM Organization"):
		return {}

	# Leads referenced by from='Lead' Opportunities that don't have an
	# owning Prospect — these are the ones with no organization unless
	# we bridge via the Lead's company_name.
	lead = frappe.qb.DocType("Lead")
	opp = frappe.qb.DocType("Opportunity")
	from_lead_party_names = (
		frappe.qb.from_(opp)
		.select(opp.party_name)
		.distinct()
		.where((opp.opportunity_from == "Lead") & opp.party_name.isnotnull() & (opp.party_name != ""))
	)
	rows = (
		frappe.qb.from_(lead)
		.select(lead.name.as_("lead"), lead.company_name)
		.where(
			lead.name.isin(from_lead_party_names) & lead.company_name.isnotnull() & (lead.company_name != "")
		)
	).run(as_dict=True)
	lead_to_company = {r["lead"]: r["company_name"] for r in rows if r["lead"] not in lead_to_prospect}
	if not lead_to_company:
		return {}

	# Materialise CRM Organization rows for distinct company names that
	# don't already exist as a CRM Organization (would also collide with
	# existing Prospect-derived orgs, since both use the same name).
	distinct_companies = set(lead_to_company.values())
	co = frappe.qb.DocType("CRM Organization")
	already = set(
		r[0] for r in frappe.qb.from_(co).select(co.name).where(co.name.isin(list(distinct_companies))).run()
	)
	to_create = distinct_companies - already
	if to_create:
		now = now_datetime()
		values = [(c, "Administrator", now, now, "Administrator", 0, c) for c in to_create]
		try:
			frappe.db.bulk_insert(
				"CRM Organization",
				fields=[
					"name",
					"owner",
					"creation",
					"modified",
					"modified_by",
					"docstatus",
					"organization_name",
				],
				values=values,
				ignore_duplicates=True,
			)
		except Exception:
			frappe.log_error(
				title="Migrator: lazy CRM Organization for lead-from Opportunity",
				message=frappe.get_traceback(),
			)

	return lead_to_company


# ---------------------------------------------------------------------------
# Customer → CRM Organization bridge for Opportunity-from-Customer rows
# ---------------------------------------------------------------------------


def _ensure_customer_organizations(source_doctype: str) -> dict[str, str]:
	"""For Opportunity rows where `opportunity_from = 'Customer'`, ensure
	a target-side CRM Organization exists for each referenced Customer,
	lazy-created from Customer data when missing.

	Strictly target-side: nothing is written to `tabProspect` or any other
	source ERPNext doctype — the migrator must not pollute the source bench.
	The bridged organization name defaults to `Customer.customer_name`
	(falling back to `Customer.name` if customer_name is empty) so the
	migrated CRM Deal carries the human-readable label.

	Returns `{customer_name: org_name}` — the chunk loop rewrites
	`Opportunity.party_name` from Customer.name to the org name so the
	dynamic-link routing writes a valid Organization reference on
	CRM Deal.
	"""
	if source_doctype != "Opportunity":
		return {}
	if not frappe.db.exists("DocType", "Customer"):
		return {}

	opp = frappe.qb.DocType("Opportunity")
	customer_ids = [
		r[0]
		for r in frappe.qb.from_(opp)
		.select(opp.party_name)
		.distinct()
		.where((opp.opportunity_from == "Customer") & opp.party_name.isnotnull() & (opp.party_name != ""))
		.run()
	]
	if not customer_ids:
		return {}

	cust = frappe.qb.DocType("Customer")
	customers = (
		frappe.qb.from_(cust)
		.select(
			cust.name,
			cust.customer_name,
			cust.owner,
			cust.creation,
			cust.modified,
			cust.modified_by,
		)
		.where(cust.name.isin(customer_ids))
	).run(as_dict=True)
	if not customers:
		return {}

	co = frappe.qb.DocType("CRM Organization")
	existing_orgs = set(r[0] for r in frappe.qb.from_(co).select(co.name).run())

	translation: dict[str, str] = {}
	orgs_to_insert: list[tuple] = []

	for cust in customers:
		# CRM Organization autoname is field:organization_name; prefer the
		# human-readable customer_name, fall back to Customer.name so an
		# organization always lands.
		org_name = cust["customer_name"] or cust["name"]
		translation[cust["name"]] = org_name

		if org_name not in existing_orgs:
			orgs_to_insert.append(
				(
					org_name,
					cust["owner"],
					cust["creation"],
					cust["modified"],
					cust["modified_by"],
					0,
					org_name,
				)
			)
			existing_orgs.add(org_name)

	if orgs_to_insert:
		frappe.db.bulk_insert(
			"CRM Organization",
			fields=[
				"name",
				"owner",
				"creation",
				"modified",
				"modified_by",
				"docstatus",
				"organization_name",
			],
			values=orgs_to_insert,
			ignore_duplicates=True,
		)

	return translation


# ---------------------------------------------------------------------------
# per-doctype migration step
# ---------------------------------------------------------------------------


def _migrate_one_doctype(source_doctype: str) -> dict:
	"""Migrate every row of one source doctype into its target.

	Returns a dict with ok/skipped/failed counts plus a sample of failed
	source-names and the most recent error message.
	"""
	target_doctype = REVERSE_DOCTYPE_MAP.get(source_doctype, "")
	if not target_doctype:
		return {
			"ok": 0,
			"skipped": 0,
			"failed": 0,
			"child_reanchored": 0,
			"last_error": "",
			"sample_failed": [],
		}

	field_pairs = _load_field_map(source_doctype, target_doctype)
	if not field_pairs:
		return {
			"ok": 0,
			"skipped": 0,
			"failed": 0,
			"child_reanchored": 0,
			"last_error": "",
			"sample_failed": [],
		}

	target_meta = frappe.get_meta(target_doctype)

	# Build the column list we'll bulk-insert. Order matters — bulk_insert
	# expects the values tuples to match this sequence exactly.
	target_cols: list[str] = []
	for f in PRESERVED_META_FIELDS:
		target_cols.append(f)
	for f in PRESERVED_META_CACHE_FIELDS:
		# include only if the target table actually has the column
		if target_meta.has_field(f) or _column_exists(target_doctype, f):
			target_cols.append(f)

	# Skip Table-type target fields — we don't bulk-insert child tables this
	# way. The child re-anchor step handles shared-schema children, and
	# Schema-reshape children are handled in api/reshape.py.
	mapped_cols: list[str] = []
	for _src, tgt in field_pairs:
		tgt_df = target_meta.get_field(tgt)
		if tgt_df is None:
			continue
		if tgt_df.fieldtype in ("Table", "Table MultiSelect"):
			continue
		mapped_cols.append(tgt)

	# Ensure each mapped column is unique and not already in target_cols.
	for c in mapped_cols:
		if c not in target_cols:
			target_cols.append(c)

	# Add naming_series with empty default if the target requires it but the
	# source doesn't carry it. We keep the source `name`, so naming_series
	# being '' is fine — name is already set explicitly.
	if target_meta.has_field("naming_series") and "naming_series" not in target_cols:
		target_cols.append("naming_series")

	# Dynamic-Link source fields (e.g. Opportunity.party_name) route to
	# different target columns at write time. Make sure every column the
	# router could touch is in the column set so values aren't dropped
	# during the tuple build in _build_target_row.
	for (src_dt, _src_field), rule in DYNAMIC_LINK_ROUTES.items():
		if src_dt != source_doctype:
			continue
		for tgt_col in (*rule["routes"].values(), rule["default_target"]):
			if tgt_col not in target_cols and target_meta.has_field(tgt_col):
				target_cols.append(tgt_col)

	# ERPNext-CRM integration tracker — Frappe CRM's
	# erpnext_crm_settings.create_custom_fields_in_frappe_crm() installs
	# `erpnext_customer` (Data) on CRM Deal so the deal records which
	# ERPNext Customer it came from. Stash the original Customer.name on
	# `opportunity_from='Customer'` deals before the party_name rewrite
	# clobbers it.
	wants_erpnext_customer = source_doctype == "Opportunity" and target_meta.has_field("erpnext_customer")
	if wants_erpnext_customer and "erpnext_customer" not in target_cols:
		target_cols.append("erpnext_customer")

	# Source-name routing: the registry's `*_TO_CRM_*` dicts may map
	# the source's `name` key to a target column (e.g. UTM Source.name →
	# CRM Lead Source.source_name). `name` never reaches the locked Field
	# Map (it's a framework field filtered both in refresh_diff and in
	# _load_field_map), so we resolve it from the registry here and pass
	# the chosen target column into _build_target_row.
	name_target_col = SUGGESTION_MAP.get(source_doctype, {}).get("name")
	if name_target_col and not target_meta.has_field(name_target_col):
		# Target doesn't have the column on this site — drop the rule.
		name_target_col = None
	if name_target_col and name_target_col not in target_cols:
		target_cols.append(name_target_col)

	# A reverse map src→tgt (for this doctype only) used during preprocess.
	src_to_tgt = {src: tgt for src, tgt in field_pairs}

	# Customer-from Opportunity bridge: ensure Prospect + CRM Organization
	# exist for every Customer referenced by an Opportunity. Returns a
	# translation map used in the chunk loop to rewrite party_name from
	# Customer.name to Prospect.name (= Customer.customer_name).
	customer_to_organization = _ensure_customer_organizations(source_doctype)

	# Lead-from Opportunity organization context: each Lead may be
	# owned by a Prospect (via Prospect.leads child rows). The map
	# is consulted in _build_target_row to populate CRM Deal.organization
	# alongside CRM Deal.lead when opportunity_from='Lead'.
	lead_to_prospect = _build_lead_to_prospect_map(source_doctype)
	lead_to_company = _ensure_lead_company_orgs(source_doctype, lead_to_prospect)

	# Read source rows in chunks via raw SQL — guarantees we see every
	# column (including `_user_tags`, `_assign`, etc.) regardless of
	# get_all's defaults.
	total = frappe.db.count(source_doctype)

	ok = 0
	failed = 0
	skipped = 0
	last_error = ""
	sample_failed: list[str] = []
	offset = 0

	src_tbl = frappe.qb.DocType(source_doctype)
	while offset < total:
		try:
			rows = (
				frappe.qb.from_(src_tbl)
				.select(src_tbl.star)
				.orderby(src_tbl.name)
				.limit(CHUNK_SIZE)
				.offset(offset)
			).run(as_dict=True)
		except Exception as e:
			last_error = f"chunk read at offset {offset}: {e}"
			frappe.log_error(
				title=f"Migrator: {source_doctype} chunk read",
				message=frappe.get_traceback(),
			)
			break
		if not rows:
			break

		values: list[tuple] = []
		for src_row in rows:
			try:
				# Customer-from Opportunity: rewrite party_name to the
				# CRM Organization name that _ensure_customer_organizations
				# materialised so the dynamic-link routing writes a valid
				# Organization reference on CRM Deal. Stash the original
				# Customer.name into _erpnext_customer first so the
				# erpnext_customer tracker on CRM Deal still records which
				# ERPNext Customer the deal came from.
				if customer_to_organization and src_row.get("opportunity_from") == "Customer":
					original_customer = src_row.get("party_name")
					if original_customer:
						src_row["_erpnext_customer"] = original_customer
					translated = customer_to_organization.get(original_customer)
					if translated:
						src_row["party_name"] = translated

				out = _build_target_row(
					src_row,
					src_to_tgt,
					target_cols,
					target_doctype,
					source_doctype,
					lead_to_prospect=lead_to_prospect,
					lead_to_company=lead_to_company,
					name_target_col=name_target_col,
				)
				values.append(out)
			except Exception as e:
				failed += 1
				last_error = str(e)[:500]
				if len(sample_failed) < SAMPLE_FAILED_LIMIT:
					sample_failed.append(src_row.get("name") or "<unknown>")
				frappe.log_error(
					title=f"Migrator: {source_doctype} row {src_row.get('name') or '<unknown>'}",
					message=frappe.get_traceback(),
				)

		if values:
			# Determine which names in this batch already exist, BEFORE the
			# insert — that's our skipped count for this chunk. Anything
			# else is genuinely new.
			batch_names = [v[0] for v in values]
			if batch_names:
				tgt_tbl = frappe.qb.DocType(target_doctype)
				pre_existing = set(
					r[0]
					for r in frappe.qb.from_(tgt_tbl)
					.select(tgt_tbl.name)
					.where(tgt_tbl.name.isin(batch_names))
					.run()
				)
			else:
				pre_existing = set()
			try:
				frappe.db.bulk_insert(
					target_doctype,
					fields=target_cols,
					values=values,
					ignore_duplicates=True,
				)
				ok += len(values) - len(pre_existing)
				skipped += len(pre_existing)
			except Exception as e:
				# Whole-chunk failure (rare — usually a schema mismatch).
				# Mark every row in the chunk as failed; the user will see
				# the error in last_error.
				failed += len(values)
				last_error = f"bulk_insert chunk at offset {offset}: {e}"
				for v in values[: SAMPLE_FAILED_LIMIT - len(sample_failed)]:
					sample_failed.append(v[0])  # name is column 0
				frappe.log_error(
					title=f"Migrator: {source_doctype} bulk_insert chunk @ offset {offset}",
					message=frappe.get_traceback(),
				)

		frappe.db.commit()  # nosemgrep: frappe-manual-commit -- per-chunk crash safety — interrupted N-row migration keeps the first floor(N/CHUNK_SIZE)*CHUNK_SIZE rows; re-run is idempotent via preserved name + ignore_duplicates
		offset += CHUNK_SIZE

	# Re-anchor shared-schema child rows (e.g. tabCRM Status Change Log)
	# via meta inspection — Table fields don't appear in the locked
	# field map anymore, so we discover them by walking source meta.
	child_reanchored = _reanchor_shared_children(source_doctype, target_doctype, target_meta)

	return {
		"ok": ok,
		"skipped": skipped,
		"failed": failed,
		"child_reanchored": child_reanchored,
		"last_error": last_error,
		"sample_failed": sample_failed,
	}


# ---------------------------------------------------------------------------
# preprocessing
# ---------------------------------------------------------------------------


def _dedup_json_list(raw: object) -> object:
	"""Return `raw` with duplicate entries removed, preserving first-seen
	order. Non-list values (NULL, malformed JSON, empty string) pass
	through unchanged so the column ends up with whatever the database
	default produces.
	"""
	if not raw or not isinstance(raw, str):
		return raw
	import json

	try:
		decoded = json.loads(raw)
	except (json.JSONDecodeError, TypeError):
		return raw
	if not isinstance(decoded, list):
		return raw
	seen: set = set()
	deduped: list = []
	for item in decoded:
		key = item if isinstance(item, (str, int, float, bool)) else json.dumps(item, sort_keys=True)
		if key in seen:
			continue
		seen.add(key)
		deduped.append(item)
	if len(deduped) == len(decoded):
		return raw  # no change — keep the original encoding
	return json.dumps(deduped)


def _build_target_row(
	src_row: dict,
	src_to_tgt: dict,
	target_cols: list[str],
	target_doctype: str,
	source_doctype: str,
	lead_to_prospect: dict[str, str] | None = None,
	lead_to_company: dict[str, str] | None = None,
	name_target_col: str | None = None,
) -> tuple:
	"""Compute a tuple of values matching `target_cols` order for one row."""
	out: dict[str, object] = {}

	# 1. preserved meta — copied straight from source
	for f in PRESERVED_META_FIELDS:
		out[f] = src_row.get(f)

	# 1b. name-routing — registries that map `name → <target_col>` (e.g.
	# UTM Source.name → CRM Lead Source.source_name). Skips the locked
	# Field Map path because `name` is filtered there.
	if name_target_col and name_target_col in target_cols:
		out[name_target_col] = src_row.get("name")

	# 2. metadata caches — copied if source has them (target column membership
	# was already enforced when target_cols was built). `_assign`,
	# `_user_tags` and `_liked_by` are JSON lists that source data
	# sometimes accumulates duplicate entries in (e.g. the same user added
	# to _assign twice by separate code paths). The desk + the CRM
	# frontend both render those lists naively, so a duplicate entry
	# shows up as a doubled avatar / chip. Strip duplicates here
	# preserving first-seen order.
	for f in PRESERVED_META_CACHE_FIELDS:
		if f in target_cols:
			out[f] = _dedup_json_list(src_row.get(f))

	# 3. mapped fields — the locked map drives the renames. Dynamic
	# Link source fields are deliberately skipped here so they don't
	# fight other source fields that legitimately map to the same
	# target column (e.g. a custom field on Opportunity → CRM Deal
	# organization). Step 5 is the sole writer for dynamic-link
	# values.
	dynamic_sources = {src_field for (src_dt, src_field) in DYNAMIC_LINK_ROUTES if src_dt == source_doctype}
	for src, tgt in src_to_tgt.items():
		if src in dynamic_sources:
			continue
		if tgt not in target_cols:
			continue
		out[tgt] = src_row.get(src)

	# 4. naming_series default — we provided `name` explicitly, so this is
	# just here to satisfy NOT NULL on targets that have the column.
	if "naming_series" in target_cols and not out.get("naming_series"):
		out["naming_series"] = src_row.get("naming_series") or ""

	# 5. Dynamic-Link routing — write the source value into the column
	# chosen by the controller field (e.g. Opportunity's party_name
	# lands on CRM Deal.lead when opportunity_from='Lead' and on
	# CRM Deal.organization when ='Prospect'). The other rule columns
	# are left with whatever step 3 wrote — so a custom field that
	# maps to organization survives in the from='Lead' case.
	for (src_dt, src_field), rule in DYNAMIC_LINK_ROUTES.items():
		if src_dt != source_doctype:
			continue
		controller_value = src_row.get(rule["controller_field"])
		value = src_row.get(src_field)
		chosen = rule["routes"].get(controller_value, rule["default_target"])
		if chosen in target_cols and value:
			out[chosen] = value

	# 6. For Opportunity from=Lead: also populate CRM Deal.organization.
	# Prefer the Prospect that owns the Lead (Prospect.leads child rows).
	# Otherwise fall back to the Lead's own company_name (a CRM
	# Organization for which is lazy-created in _ensure_lead_company_orgs).
	# Without one or the other, the deal lands with organization=NULL and
	# the desk renders the title as "undefined" because CRM Deal's
	# title_field is `organization`.
	if (
		source_doctype == "Opportunity"
		and src_row.get("opportunity_from") == "Lead"
		and "organization" in target_cols
	):
		lead = src_row.get("party_name")
		owning = (lead_to_prospect or {}).get(lead) or (lead_to_company or {}).get(lead)
		if owning:
			out["organization"] = owning

	# 7. ERPNext-Customer tracker — when an Opportunity is
	# `opportunity_from='Customer'` the chunk loop stashes the original
	# Customer.name into `_erpnext_customer` before rewriting party_name
	# to the bridged Prospect. Carry it through to the target column.
	if "erpnext_customer" in target_cols and src_row.get("_erpnext_customer"):
		out["erpnext_customer"] = src_row["_erpnext_customer"]

	# Build the tuple in target_cols order. None for any column we didn't
	# populate — the database default takes over (typically NULL).
	return tuple(out.get(c) for c in target_cols)


def _load_field_map(source_doctype: str, target_doctype: str) -> list[tuple[str, str]]:
	"""Return [(source_field, target_field), ...] from the locked Field Map.

	Skips meta fields (handled separately by PRESERVED_META_FIELDS).
	"""
	fm = frappe.qb.DocType(FIELD_MAP_DOCTYPE)
	rows = (
		frappe.qb.from_(fm)
		.select(fm["source"], fm.target)
		.where((fm.s_doctype == source_doctype) & (fm.t_doctype == target_doctype))
	).run(as_dict=True)
	pairs: list[tuple[str, str]] = []
	for r in rows:
		if r["source"] in PRESERVED_META_FIELDS:
			continue
		pairs.append((r["source"], r["target"]))
	return pairs


def _column_exists(doctype: str, column: str) -> bool:
	"""Return True if `tab<doctype>` has a column named `column`."""
	try:
		cols = frappe.db.get_table_columns(doctype)
		return column in cols
	except Exception:
		return False


# ---------------------------------------------------------------------------
# child-row re-anchoring (shared-schema only)
# ---------------------------------------------------------------------------

# Explicit overrides for the source → target parentfield mapping inside
# _reanchor_shared_children. Use when the source has an extra Table
# field (e.g. a custom_ duplicate) that should be merged into the
# canonical CRM target field instead of being skipped for lack of a
# same-name match. Keyed by (source_doctype, source_field) → target_field.
SHARED_CHILD_FIELD_MERGES: dict[tuple[str, str], str] = {
	# (Currently empty.) Populate when a source has an extra Table field
	# whose child doctype IS the same as the target's canonical Table,
	# and the rows should be folded into it rather than re-anchored
	# under a different field name. When the source/target child
	# doctypes differ (e.g. CRM Stage Change Log vs CRM Status Change
	# Log), use a `api/reshape.py` function instead — see
	# `reshape_opportunity_stage_logs`.
}


def _reanchor_shared_children(
	source_doctype: str,
	target_doctype: str,
	target_meta,
) -> int:
	"""Rewrite parenttype/parentfield on child rows whose child doctype is
	identical on both source and target meta.

	Discovery is via meta inspection — we don't read the locked field
	map for this. Table fields are deliberately hidden from the diff
	UI (they aren't column-mapped); shared-schema Tables still need
	re-anchoring, so we walk source meta and match every Table field
	whose name + options align with a Table on target meta. Schema-
	reshape children (where the child doctype itself changes) live in
	`api/reshape.py` and never enter this loop.

	`SHARED_CHILD_FIELD_MERGES` overrides the default same-name match
	for cases where a source has an extra Table field that should
	merge into the canonical target field (e.g.
	Opportunity.custom_status_change_log → CRM Deal.status_change_log).

	Returns the total number of child rows updated across all eligible
	child doctypes.
	"""
	source_meta = frappe.get_meta(source_doctype)
	total = 0
	seen: set[tuple[str, str]] = set()

	for src_df in source_meta.fields:
		if src_df.fieldtype not in ("Table", "Table MultiSelect"):
			continue
		if not src_df.options:
			continue
		# Decide which target field this source field re-anchors to:
		# explicit merge override first, else same-name fallback.
		merge_target = SHARED_CHILD_FIELD_MERGES.get((source_doctype, src_df.fieldname))
		tgt_fieldname = merge_target or src_df.fieldname
		tgt_df = target_meta.get_field(tgt_fieldname)
		if tgt_df is None or tgt_df.fieldtype != src_df.fieldtype:
			continue
		if (tgt_df.options or "") != (src_df.options or ""):
			# different child doctype → cross-table reshape, see api/reshape.py
			continue
		child_dt = src_df.options
		src_field = src_df.fieldname
		tgt_field = tgt_fieldname

		key = (child_dt, src_field)
		if key in seen:
			continue
		seen.add(key)

		# Count rows that still need re-anchoring BEFORE the UPDATE — that
		# count IS the number we'll be moving. Re-runs see 0 here because
		# the previous run already moved them all to the target parenttype.
		to_move = frappe.db.count(
			child_dt,
			filters={
				"parenttype": source_doctype,
				"parentfield": src_field,
			},
		)
		if to_move:
			child_tbl = frappe.qb.DocType(child_dt)
			(
				frappe.qb.update(child_tbl)
				.set(child_tbl.parenttype, target_doctype)
				.set(child_tbl.parentfield, tgt_field)
				.where((child_tbl.parenttype == source_doctype) & (child_tbl.parentfield == src_field))
				.run()
			)
			total += int(to_move)

	return total


# ---------------------------------------------------------------------------
# pre-flight: verify upstream lookups exist before migrating a parent
# ---------------------------------------------------------------------------

# Each parent maps to the upstream lookup target doctypes whose Link values
# may appear on its rows. Computed from the registry: for every parent's
# Link field whose target options is one of our migration target lookup
# doctypes, that target needs to be populated before this parent runs.
_PARENT_DEPENDENCIES = {
	"Lead": ["CRM Industry", "CRM Territory", "CRM Lead Source"],
	"Opportunity": [
		"CRM Industry",
		"CRM Territory",
		"CRM Lead Source",
		"CRM Lost Reason",
		"CRM Organization",  # party_name → Prospect → CRM Organization
	],
	"Prospect": ["CRM Industry", "CRM Territory"],
	# Self-references aren't pre-checked — the bulk_insert handles the same
	# table fine regardless of order, and Frappe Link fields aren't FK-enforced.
	"Territory": [],
	"Item": [],
	"Industry Type": [],
	"UTM Source": [],
	"Opportunity Lost Reason": [],
}


def _preflight_link_check(source_doctype: str) -> str | None:
	"""Return an explanatory string if the parent can't run yet, else None.

	A parent step is blocked if any of its upstream CRM lookup tables is
	empty when the source has Link values pointing into the corresponding
	source-side lookup. The check is deliberately coarse — empty target
	table is the failure mode we care about; row-by-row mismatches are
	caught later by the bulk_insert path.
	"""
	deps = _PARENT_DEPENDENCIES.get(source_doctype, [])
	missing: list[str] = []
	for target_lookup in deps:
		try:
			n = frappe.db.count(target_lookup)
		except Exception:
			n = 0
		if n == 0:
			# Distinguish "target table empty because nothing migrated yet"
			# from "no source rows reference this lookup at all". Cheap
			# heuristic: if the source-side equivalent has rows, this is a
			# real prereq miss.
			source_lookup = _crm_to_source_doctype(target_lookup)
			if source_lookup:
				try:
					src_n = frappe.db.count(source_lookup)
				except Exception:
					src_n = 0
				if src_n > 0:
					missing.append(target_lookup)

	if missing:
		return (
			f"Upstream lookups not yet migrated: {', '.join(missing)}. "
			f"Run the per-tab migration for those source doctypes first, "
			f"or use the top-level Run Migration button to migrate all."
		)
	return None


def _crm_to_source_doctype(crm_doctype: str) -> str | None:
	"""Reverse-lookup helper for _preflight_link_check.

	REVERSE_DOCTYPE_MAP is keyed by ERPNext source name and yields the CRM
	target name. We need the inverse: given a CRM target, what's its
	ERPNext source?
	"""
	for src, tgt in REVERSE_DOCTYPE_MAP.items():
		if tgt == crm_doctype:
			return src
	return None
